#!/usr/bin/env python3

import sys
import os
import numpy
import scipy.ndimage
import nibabel
import skimage.morphology

if len(sys.argv) < 2:
    print("Usage " + sys.argv[0] + " <subjid>")
    quit()

subjID = sys.argv[1]

T1NII = nibabel.load(subjID + '_t1.nii.gz')
T1IMG = T1NII.get_fdata()

MarkerNII = nibabel.load(subjID + '_t2OtsuSkull.nii.gz')
MarkerIMG = numpy.uint8(MarkerNII.get_fdata() > 0)

DKTNII = nibabel.load(subjID + '_dkt.nii.gz')
DKTIMG = numpy.uint16(DKTNII.get_fdata())

InnerMarker = numpy.logical_not(scipy.ndimage.binary_dilation(MarkerIMG, iterations = 5))

MarkerIMG[InnerMarker] = 2
W = skimage.morphology.watershed(-T1IMG, MarkerIMG)

NewNII = nibabel.Nifti1Image(numpy.uint8(W), T1NII.affine)
nibabel.save(NewNII, subjID + "_ws.nii.gz")
NewNII = nibabel.Nifti1Image(numpy.uint8(InnerMarker), T1NII.affine)
nibabel.save(NewNII, subjID + "_inner_marker.nii.gz")
